version: '3.8'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    command: npm run server
    ports:
      - "5000:5000"
    depends_on:
      - mongo  
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/Medicare
      - JWT_SECRET_KEY=BI/AhADj/Nu2AUJhXHMUrFcT7CvNvvrsPLluHlEHW1gT1/qh/v0suSV2Oq12H29KKfIk2joGyQT6hdvlSMm6mNMI4/WpVHh4slEwmgwLfFn/v7MQOI6iab0KfUF7fa6ueC5AkyWXtMSaO76LEQsHSYiEcblM12K8YFGfcryvf1Fr5iDTZEhKrLETdTUxpKPXj3ttF88iSaidINvbOr4wZg+3UcC9SCTvUpQtPquOOCDEyOIRXQn7lGVJRxrYFsuCPOIoA1pIrskOC8VIhqGO+jSP4dmApgb9BUlQoEQC/L1vRv4iw5fgr+7fnIKSYVITwXdfNJ5kUhHXyh8M3BlMDg==
      - STRIPE_SECRET_KEY=sk_test_51PPOrF00lMJFZZxsXZkzJNfMaMmXrpyF5fCBr04DcaQ6qwQ7H4I3pZtqAXL9nCIT5D6Ti1vpxK3ABzteAWrZfT9n00RQ3IlGok
      - CLIENT_SITE_URL=http://localhost:5173
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    command: npm run dev
    ports:
      - "5177:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:5000
  
volumes:
  mongo-data:

